# Generated by Django 5.1.5 on 2025-02-02 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_task',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
